### ISSUE TITLE
64-bit so

### ISSUE THREAD

**Issue by tpapagiannis** [LeoIsasmendi/exampleHikvisionSDKPlayer#6]
Hi, library is very nice, but it does not have 64-bit so files, so google play does not permit publishing.
Are you going to make 64-bit versions of so files ?

**Comment by LeoIsasmendi** [comment]
Hi @tpapagiannis , yes this demo doesn't have support for 64bit because I'm not the owner of the source code of SADP library or any Hickvision library.
Currently, I'm using a binary provided by Hickvision for educational purposes and it's not for publishing. If you want an application that uses the Hickvision SDK libs and can be published, you need to contact Hickvision by mail
Regards!!

**Comment by drdinfotech** [comment]
> Hi, library is very nice, but it does not have 64-bit so files, so google play does not permit publishing. Are you going to make 64-bit versions of so files ?you find any solutions  regarding  this issue ?
